### ISSUE TITLE
Footer (alignement images)

### ISSUE THREAD

**Issue by nico3333fr** [Paris-Web/pw-design-system#26]
Plop,

en regardant le footer sur mobile (< à 720px), je m'aperçois que les icônes de réseaux sociaux sont bizarrement centrées, au lieu d'être alignées à gauche.

A vue de nez, ça vient de :
```css
.columns-list--follow {text-align: center; } /* qui devrait être à left */
```

J'ai pas osé y toucher, j'ai pas eu le temps de vérifier que cela n'impactait pas autre chose, faut que je me monte le site en local pour voir ça. :)
