### ISSUE TITLE
Modifs (pour 2019)

### ISSUE THREAD

**Issue by joachimesque** [Paris-Web/pw-design-system#76]
# Module `portrait`

[screenshot_2018-10-01 paris web les membres 1](https://user-images.githubusercontent.com/1781070/46289480-7fcaf900-c589-11e8-9542-16e10c2ef56a.jpg)

````CSS
.portrait__links {
    margin: -2.5em auto 0;
    vertical-align: bottom;
    display: -webkit-box;
    display: flex;
    -webkit-box-pack: flex-end;
    justify-content: flex-end;
    min-height: 28.8px;
    min-height: 2rem;
}
.icon.icon--social {
    height: 22.16px;
    height: calc(1.4rem + 2px);
    width: 22.16px;
    width: calc(1.4rem + 2px);
    background-color: white;
    border-radius: 50%;
    border: 1px solid white;
}
.icon-link:visited {
    color: #585462;
}
````

# Page Membres

https://www.paris-web.fr/association/membres.php

Ajuster la chromie de tous les portraits

# Page lieux

https://www.paris-web.fr/lieux/

Voir si OSM permet de changer les couleurs d'affichage comme Google Maps
